media_entity_gist_embed.settings:
  type: config_object
  label: 'Media entity Gist embed settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for thumbnails'

media_entity.bundle.type.gist_embed:
  type: mapping
  label: 'Gist embed type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
    use_github_api:
      type: boolean
      label: 'Whether to use github api or not'
